#!/bin/bash
set -e
#set -x

#######################################
#	See README.me
#
#	Arguments:
#		repo (string): repo name
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function main() {
	local readonly USAGE="Usage: ./deploy repo destination"
	declare -a repos=("Sol.dk-RC" "Wemail-RC")

	if [ "${#}" -ne 2 ]; then
		err "Error: two arguments are required"
		err "${USAGE}"
		err "Available repo:"
		printf '\t%s\n' "${repos[@]}"
		return 1
	fi

	# In Bash, it's easy to check if an array contains an element
	if [[ ! ${repos[*]} =~ (^|[[:space:]])"${1}"($|[[:space:]]) ]]; then
		err "Error: invalid argument provided. Available repo:"
		printf '\t%s\n' "${repos[@]}"
		return 1
	fi

	local readonly dest="${2}"

	echo -e "UPDATING WEBMAIL: ${dest}\n"

	# Fetch/update webmail
	get_rc "${dest}"
	get_skin "${dest}"
	get_lang "${dest}"

	# Fetch/update plugins
	get_plugin "${dest}" RC-Plugin-wblist
	get_plugin "${dest}" RC-Plugin-spamlevel
	get_plugin "${dest}" RC-Plugin-mailcore_loglogin
	get_raim "${dest}"
	get_recurrent "${dest}"
	get_plugin "${dest}" RC-Plugin-managesieve

	local readonly skin=$(cat "config/${dest}/custom.inc.php" | grep "'skin'" | cut -d"'" -f4)
	rm "${dest}/plugins/managesieve/config.inc.php" "${dest}/plugins/managesieve/skins/${skin}"
	ln -s "../../config/managesieve.conf" "${dest}/plugins/managesieve/config.inc.php"
	ln -s "elastic" "${dest}/plugins/managesieve/skins/${skin}"

	# Fix permissions
	#sudo chown -R www-data:www-data "${dest}" config/ repos/
	#sudo chmod -R ug+rwx "${dest}" config/ repos/

	return 0
}

#######################################
#	Check if current RoundCube if up to date
#	If not: delete and fetch latest release
#
#	Arguments:
#		dest (string): rc_root name
#		repo (string): name of remote repo
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function get_rc() {
	if [ "${#}" -ne 1 ]; then
		err "Error: missing arguments"
		err "Usage: get_rc dest"
		return 1
	fi

	local readonly dest="${1}"

	echo "Updating Roundcube:"

	local readonly latest=$(curl --silent "https://api.github.com/repos/roundcube/roundcubemail/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
	local readonly current=$(cat "${dest}/CHANGELOG" | grep RELEASE | head -1 | cut -d' ' -f2)

	# Update Roundcube if current is either outdated or nonexistant
	if [[ -z "${current}" ]] || [[ "${latest}" != "${current}" ]]; then
		[[ -d "${dest}" ]] && mv "${dest}" "${dest}.bak-$(date +'%Y-%m-%d--%H-%M')"

		wget -c "https://github.com/roundcube/roundcubemail/releases/download/${latest}/roundcubemail-${latest}-complete.tar.gz" -O - | tar -xz
		mv "roundcubemail-${latest}" "${dest}"
		chmod -R ug+rw "${dest}/temp" "${dest}/logs"
		rm -rf "${dest}/installer"

		# Fetch RC config
		[[ -d "${dest}/config" ]] && rm -rf "${dest}/config"
		ln -s "../config/${dest}/" "${dest}/config"

		# Fetch managesieve config
		#local readonly skin=$(cat "config/${dest}/custom.inc.php" | grep "'skin'" | cut -d"'" -f4)
		#ln -s "../../config/managesieve.conf" "${dest}/plugins/managesieve/config.inc.php"
		#ln -s "elastic" "${dest}/plugins/managesieve/skins/${skin}"

		# Apply Jesper's patch
		#echo "${MANAGESIEVE_PATCH}" | sed -e "s/app.sol.dk/${dest}/g" | patch -p 0
	else
		echo "Already up to date."
	fi

	return 0
}

#######################################
#	Fetch/Update skin
#	Link from rc_root
#
#	Arguments:
#		dest (string): rc_root name
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function get_skin() {
	if [ "${#}" -ne 1 ]; then
		err "Error: no argument provided"
		err "Usage: get_skin dest"
		return 1
	fi

	local readonly dest="${1}"
	echo -e "\nUpdating skins:"

	# Check if passed dest exists
	if [[ ! -d "${dest}" ]]; then
		err "Error: destination folder does not exist"
		return 1
	fi

	# Check if deploy key is found
	local readonly deploy_key="$(pwd)/deploy_keys/mailcore_deploy_skin"
	if [[ ! -f "${deploy_key}" ]]; then
		err "Error: deploy key for was not found: ${deploy_key}"
		return 1
	fi

	# Update if the plugin exists, clone otherwise
	mkdir -p repos/
	if [[ -d repos/RC-Skin/ ]]; then
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git -C repos/RC-Skin/ pull
	else
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git clone git@github.com:Fjordmail/RC-Skin.git repos/RC-Skin/
	fi

	# Put skin in rc_root/skins/
	for f in `command ls -d repos/RC-Skin/skins/*`; do
		# $f = repos/RC-Skin/skins/sol
		# $skin = sol

		# Skin name
		local skin=$(echo "${f}" | rev | cut -d'/' -f1 | rev)

		# Create link if it doesn't exist in $dest/skins
		[[ ! -d "${dest}/skins/${skin}" ]] && ln -s "../../${f}" "${dest}/skins/${skin}"
	done

	return 0
}

#######################################
#	Fetch/Update lang
#	Link from rc_root
#
#	Arguments:
#		dest (string): rc_root name
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function get_lang() {
	if [ "${#}" -ne 1 ]; then
		err "Error: no argument provided"
		err "Usage: get_skin dest"
		return 1
	fi

	local readonly dest="${1}"
	echo -e "\nUpdating langs:"

	# Check if passed dest exists
	if [[ ! -d "${dest}" ]]; then
		err "Error: destination folder does not exist"
		return 1
	fi

	# Check if deploy key is found
	local readonly deploy_key="$(pwd)/deploy_keys/mailcore_deploy_lang"
	if [[ ! -f "${deploy_key}" ]]; then
		err "Error: deploy key for was not found: ${deploy_key}"
		return 1
	fi

	# Update if the plugin exists, clone otherwise
	mkdir -p repos/
	if [[ -d repos/RC-Lang/ ]]; then
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git -C repos/RC-Lang/ pull
	else
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git clone git@github.com:Fjordmail/RC-Lang.git repos/RC-Lang/
	fi

	local readonly product_name=$(cat "config/${dest}/custom.inc.php" | grep "'product_name'" | cut -d"'" -f4)

	# Link changed files from rc_root
	for f in `find repos/RC-Lang/ -type f -not -path "repos/RC-Lang/.git*"`; do
		# $f = repos/RC-Lang/dir/file
		# $to = $dest/dir/file
		local to="${dest}/$(echo ${f} | cut -d'/' -f3-)"

		# Backup original
		[[ ! -f "${to}.original" ]] && mv "${to}" "${to}.original"

		# Remove previous and copy original
		[[ -f "${to}" ]] && rm "${to}"
		cp "${to}.original" "${to}"

		# Append custom lang entries
		cat "${f}" >> "${to}"

		# Update product_name
		sed -i "s/product_name/${product_name}/g" "${to}"
	done

	return 0
}

#######################################
#	Fetch/Update plugin and link from rc_root
#
#	Arguments:
#		dest (string): rc_root name
#		repo (string): name of plugin repo
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function get_plugin() {
	if [[ "${#}" -lt 2 ]] || [[ "${#}" -gt 3 ]]; then
		err "Error: invalid number of arguments"
		err "Usage: get_plugin dest repo [branch]"
		return 1
	fi

	local readonly dest="${1}"
	local readonly repo="${2}" # RC-Plugin-xxx
	local readonly plugin_name=$(echo "${repo}" | cut -d'-' -f3) # xxx
	local readonly branch="master"
	[[ "${#}" -eq 3 ]] && branch="${3}"

	echo -e "\nUpdating ${2}:"

	# Check if passed dest exists
	if [[ ! -d "${dest}" ]]; then
		err "Error: destination folder does not exist"
		return 1
	fi

	# Check if deploy key is found
	local readonly deploy_key="$(pwd)/deploy_keys/mailcore_deploy_${plugin_name}"
	if [[ ! -f "${deploy_key}" ]]; then
		err "Error: deploy key for was not found: ${deploy_key}"
		return 1
	fi

	# Update if the plugin exists, clone otherwise
	mkdir -p repos/
	if [[ -d "repos/${repo}" ]]; then
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git -C "repos/${repo}" pull
	else
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git clone -b "${branch}" "git@github.com:Fjordmail/${repo}.git" "repos/${repo}"
	fi

	# Install plugin to rc_root with a link
	[[ -f "${dest}/plugins/${plugin_name}" ]] && rm "${dest}/plugins/${plugin_name}"
	[[ -L "${dest}/plugins/${plugin_name}" ]] && rm "${dest}/plugins/${plugin_name}"
	ln -s "../../repos/${repo}" "${dest}/plugins/${plugin_name}"

	return 0
}

#######################################
#	Check if current plugins/raim-$dest if up to date
#	If not:
#		- Delete old
#		- Build
#		- Link from rc_root
#
#	Arguments:
#		dest (string): rc_root name
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function get_raim() {
	local readonly deploy_key="$(pwd)/deploy_keys/mailcore_deploy_raim"

	if [ "${#}" -ne 1 ]; then
		err "Error: no argument provided"
		err "Usage: get_raim dest"
		return 1
	fi

	echo -e "\nUpdating RAIM:"

	# Check if passed dest exists
	local readonly dest="${1}"
	if [[ ! -d "${dest}" ]]; then
		err "Error: destination folder does not exist"
		return 1
	fi

	# Check if deloy key is found
	if [[ ! -f "${deploy_key}" ]]; then
		err "Error: deploy key for was not found: ${deploy_key}"
		return 1
	fi

	# Check if raim is out of date or not existant
	if should_be_updated "repos/raim-${dest}"; then
		# Delete existing
		rm -rf "repos/raim-${dest}"
		rm -rf "${dest}/password-reset"
		rm -rf "${dest}/registration"

		# Fetch latest
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git clone -b master git@github.com:Fjordmail/RAIM.git "repos/raim-${dest}"

		# Fetch raim config
		ln -s "../../../../../config/${dest}/raim_shared_config.js" "repos/raim-${dest}/packages/shared/src/config.js"
		ln -s "../../../../config/${dest}/raim_registration.env" "repos/raim-${dest}/packages/registration/.env"
		ln -s "../../../../config/${dest}/raim_password-reset.env" "repos/raim-${dest}/packages/password-reset/.env"

		# Build
		cd "repos/raim-${dest}"
		yarn install
		yarn build
		cd ../../
	else
		echo "Already up to date."
	fi

	# Install plugin to rc_root with links
	[[ ! -L "${dest}/password-reset" ]] && ln -s "../repos/raim-${dest}/packages/password-reset/build" "${dest}/password-reset"
	[[ ! -L "${dest}/registration" ]] && ln -s "../repos/raim-${dest}/packages/registration/build" "${dest}/registration"

	return 0
}

#######################################
#	Fetch/Update RC-Plugin-recurrent
#	Create required links
#
#	Arguments:
#		dest (string): rc_root name
#	Returns:
#		1 upon error
#		0 upon success
#######################################
function get_recurrent() {
	if [ "${#}" -ne 1 ]; then
		err "Error: no argument provided"
		err "Usage: get_recurrent dest"
		return 1
	fi

	local readonly dest="${1}"
	echo -e "\nUpdating RC-Plugin-recurrent:"

	# Check if passed dest exists
	if [[ ! -d "${dest}" ]]; then
		err "Error: destination folder does not exist"
		return 1
	fi

	# Check if deploy key is found
	local readonly deploy_key="$(pwd)/deploy_keys/mailcore_deploy_recurrent"
	if [[ ! -f "${deploy_key}" ]]; then
		err "Error: deploy key for was not found: ${deploy_key}"
		return 1
	fi

	# Remove links, so the local repo can be updated
	[[ -L "repos/RC-Plugin-recurrent-${dest}/vendor/Config.php" ]] && rm "repos/RC-Plugin-recurrent-${dest}/vendor/Config.php"
	[[ -L "repos/RC-Plugin-recurrent-${dest}/vendor/spa" ]] && rm "repos/RC-Plugin-recurrent-${dest}/vendor/spa"

	# Fetch latest
	if [[ -d "repos/RC-Plugin-recurrent-${dest}" ]]; then
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git -C "repos/RC-Plugin-recurrent-${dest}" pull
	else
		GIT_SSH_COMMAND="ssh -i '${deploy_key}' -o IdentitiesOnly=yes" \
			git clone git@github.com:Fjordmail/RC-Plugin-recurrent.git "repos/RC-Plugin-recurrent-${dest}"
	fi

	# Recreate the links
	ln -s "../../../config/${dest}/recurrent-Config.php" "repos/RC-Plugin-recurrent-${dest}/vendor/Config.php"
	ln -s "../../raim-${dest}/packages/account/build" "repos/RC-Plugin-recurrent-${dest}/vendor/spa"

	# Install plugin to rc_root/plugins
	[[ ! -L "${dest}/plugins/recurrent" ]] && ln -s "../../repos/RC-Plugin-recurrent-${dest}" "${dest}/plugins/recurrent"

	return 0
}

#######################################
#       Check if local git repo is up to date with remote
#
#       Arguments:
#               repo (string): repo path
#       Returns:
#               0 if it should be updated
#               1 otherwise
#######################################
function should_be_updated() {
        if [ "${#}" -ne 1 ]; then
                err "Error: no argument provided"
                err "Usage: should_be_updated repo"
                return 1
        fi

        local readonly repo="${1}"

        [[ ! -d "${repo}" ]] && return 0
        [[ ! -d "${repo}/.git" ]] && return 0
        [[ "$(git --git-dir=${repo}/.git/ status -uno | grep -c 'Your branch is up to date with ')" -ne 1 ]] && return 0

        return 1
}

# Print to stderr
function err() {
	echo "${*}" >&2
}

# Jesper's managiesieve patch to disable the redirect action as an ext
readonly MANAGESIEVE_PATCH="--- app.sol.dk/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php	2021-02-08 20:29:40.000000000 +0100
+++ app.sol.dk/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.new.php	2021-04-26 21:44:01.906015211 +0200
@@ -2102,8 +2102,9 @@
             \$select_action->add(\$this->plugin->gettext('messagemoveto'), 'fileinto');
         if (in_array('fileinto', \$this->exts) && in_array('copy', \$this->exts))
             \$select_action->add(\$this->plugin->gettext('messagecopyto'), 'fileinto_copy');
-        \$select_action->add(\$this->plugin->gettext('messageredirect'), 'redirect');
-        if (in_array('copy', \$this->exts))
+        if (in_array('redirect', \$this->exts))
+            \$select_action->add(\$this->plugin->gettext('messageredirect'), 'redirect');
+        if (in_array('redirect', \$this->exts) && in_array('copy', \$this->exts))
             \$select_action->add(\$this->plugin->gettext('messagesendcopy'), 'redirect_copy');
         if (in_array('reject', \$this->exts))
             \$select_action->add(\$this->plugin->gettext('messagediscard'), 'reject');
"

main "${@}"; exit
